bot:
  name: Forkov_bot
  token: 6909314583:AAFHvyBZDHYUfz9K2tOn3fNDIAvIhAGcZrU


monitor:
  endpoint:
    start: http://localhost:9090/api/v1/start
    stop: http://localhost:9090/api/v1/stop
    url: http://localhost:9090/api/v1/urls
    block: http://localhost:9090/api/v1/block/





answer:
  command:
    help: "Привет, я телеграм бот для отслеживания товаров.\n\nМои команды: \n/help\n/start\n/status"