bot:
  name: Forkov_bor
  token: 6909314583:AAFHvyBZDHYUfz9K2tOn3fNDIAvIhAGcZrU


monitor:
  urls:
    file:
      name: urls.txt
  endpoint:
    start: http://localhost:9090/api/v1/start
    stop: http://localhost:9090/api/v1/stop
    url: http://localhost:9090/api/v1/urls





answer:
  command:
    help: "Привет, я телеграм бот для отслеживания товаров.\n\nМои команды: \n\\help\n/start\n/stop\n/settings\n/status"